# Example `alai.toml` configuration file.

[repo]
name = "alai"
wal = "repo/alai.wal"
package_dir = "repo/alai"
source_dir = "repo/cache/src"
target_dir = "repo/cache/pkg"

[[database]]
name = "core"

[[database]]
name = "extra"

[[database]]
name = "alai"
repo = "repo/alai"
