# Example `alai.toml` configuration file.

[repo]
name = "alai"
package_dir = "repo/alai"
wal = "repo/alai.wal"

[[database]]
name = "core"

[[database]]
name = "extra"

[[database]]
name = "alai"
repo = "repo/alai"
